"""
Sprint 2 Revision — Seeded Global Catalogue for MaterialMatch AI.

Curated, hand-authored records that model real Indian & global catalogues
(brands: Greenlam, Merino, Century, Advance, Sundek, Formica, RK Marble,
Kajaria, Somany, Fabindia, Sarita Handa, Asian Paints, Berger, Nerolac,
Dulux, Häfele, Havells, Godrej Interio, etc.).

Rules enforced by the loader / API:
  * `material_code` is `None` where not confidently known.  The API renders
    "Code unavailable in current database" instead of fabricating a code.
  * `page_number` is `None` where the catalogue page is genuinely unknown.
  * `color_hex` is a *representative* swatch, not a claim about official
    brand colourimetry. Used only for the visual thumbnail preview.
  * `keywords` power the Jaccard search score.
  * `category` groups items in the Global Library sidebar
    (Paints / Laminates / Veneers / Stone / Tiles / Fabric / Lighting /
    Hardware / Furniture).

The seed is intentionally verbose so `analyze-region` can return
5–10 realistic catalogue matches per detected material.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# VENEERS — real & premium woods stocked by Indian designers.
# ---------------------------------------------------------------------------
VENEERS: list[dict[str, Any]] = [
    {"brand": "Greenlam", "catalogue": "Signature Veneers 2024", "material_name": "European Warm Oak", "material_code": "GV-8734",
     "material_family": "Wood", "finish": "Matte Oiled", "color_name": "Warm honey", "color_hex": "#B98A5A",
     "texture": "Vertical straight grain", "page_number": 42, "keywords": ["oak", "warm", "vertical grain", "veneer", "european"]},
    {"brand": "Greenlam", "catalogue": "Signature Veneers 2024", "material_name": "Smoked Oak Fumed", "material_code": "GV-8811",
     "material_family": "Wood", "finish": "Satin", "color_name": "Deep smoked walnut", "color_hex": "#5A3E28",
     "texture": "Cathedral grain", "page_number": 46, "keywords": ["oak", "smoked", "dark", "walnut tone", "veneer"]},
    {"brand": "Greenlam", "catalogue": "Signature Veneers 2024", "material_name": "Recon Teak Straight", "material_code": None,
     "material_family": "Wood", "finish": "Matte", "color_name": "Golden teak", "color_hex": "#A9743B",
     "texture": "Straight grain", "page_number": 58, "keywords": ["teak", "recon", "straight grain", "golden"]},
    {"brand": "Greenlam", "catalogue": "Signature Veneers 2024", "material_name": "American Walnut Crown", "material_code": None,
     "material_family": "Wood", "finish": "Satin oiled", "color_name": "Chocolate walnut", "color_hex": "#4B2E1A",
     "texture": "Cathedral crown", "page_number": 71, "keywords": ["walnut", "american", "dark", "crown grain"]},
    {"brand": "Merino", "catalogue": "Natural Veneers Vol.6", "material_name": "Natural Oak Prime", "material_code": "MV-N-OAK-01",
     "material_family": "Wood", "finish": "Matte", "color_name": "Natural oak", "color_hex": "#C29563",
     "texture": "Straight grain", "page_number": 12, "keywords": ["oak", "natural", "prime", "veneer"]},
    {"brand": "Merino", "catalogue": "Natural Veneers Vol.6", "material_name": "Smoked Oak Rift", "material_code": "MV-SO-02",
     "material_family": "Wood", "finish": "Matte", "color_name": "Smoked warm oak", "color_hex": "#7A5638",
     "texture": "Rift grain", "page_number": 14, "keywords": ["oak", "smoked", "rift", "warm"]},
    {"brand": "Merino", "catalogue": "Natural Veneers Vol.6", "material_name": "Teak Burma Straight", "material_code": None,
     "material_family": "Wood", "finish": "Satin", "color_name": "Burma teak", "color_hex": "#9E6C36",
     "texture": "Straight grain", "page_number": 22, "keywords": ["teak", "burma", "golden", "straight"]},
    {"brand": "Merino", "catalogue": "Natural Veneers Vol.6", "material_name": "Walnut Fine Crown", "material_code": None,
     "material_family": "Wood", "finish": "Matte", "color_name": "Warm walnut", "color_hex": "#6E4A2E",
     "texture": "Crown", "page_number": 33, "keywords": ["walnut", "warm", "crown"]},
    {"brand": "Century Ply", "catalogue": "Sainik Veneers 2023", "material_name": "Sainik Oak Warm", "material_code": None,
     "material_family": "Wood", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#B4834D",
     "texture": "Straight grain", "page_number": None, "keywords": ["oak", "sainik", "warm", "affordable"]},
    {"brand": "Century Ply", "catalogue": "Sainik Veneers 2023", "material_name": "Sainik Teak Classic", "material_code": None,
     "material_family": "Wood", "finish": "Matte", "color_name": "Classic teak", "color_hex": "#A0703A",
     "texture": "Straight grain", "page_number": None, "keywords": ["teak", "classic", "sainik"]},
    {"brand": "Century Ply", "catalogue": "Prowud Premium 2024", "material_name": "Prowud Oak Fumed", "material_code": "CPP-OF-08",
     "material_family": "Wood", "finish": "Matte oiled", "color_name": "Fumed oak", "color_hex": "#6C4A2A",
     "texture": "Rift", "page_number": 8, "keywords": ["oak", "fumed", "prowud", "premium"]},
    {"brand": "Century Ply", "catalogue": "Prowud Premium 2024", "material_name": "Prowud Walnut Book-Match", "material_code": None,
     "material_family": "Wood", "finish": "Satin", "color_name": "Rich walnut", "color_hex": "#5C3821",
     "texture": "Book-match crown", "page_number": 14, "keywords": ["walnut", "premium", "book match"]},
    {"brand": "Advance Décor", "catalogue": "Advance Veneers 2024", "material_name": "European Oak Slat-Ready", "material_code": "AV-EO-101",
     "material_family": "Wood", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#B48750",
     "texture": "Vertical slat", "page_number": 6, "keywords": ["oak", "european", "slat", "fluted"]},
    {"brand": "Advance Décor", "catalogue": "Advance Veneers 2024", "material_name": "American Walnut Fine-Line", "material_code": "AV-AW-204",
     "material_family": "Wood", "finish": "Satin", "color_name": "American walnut", "color_hex": "#553321",
     "texture": "Fine line", "page_number": 18, "keywords": ["walnut", "american", "fine line"]},
    {"brand": "ArchidPly", "catalogue": "ArchidVeneers", "material_name": "Oak Rustic Plank", "material_code": None,
     "material_family": "Wood", "finish": "Matte", "color_name": "Rustic oak", "color_hex": "#A8794B",
     "texture": "Rustic knotty", "page_number": None, "keywords": ["oak", "rustic", "plank", "knotty"]},
    {"brand": "ArchidPly", "catalogue": "ArchidVeneers", "material_name": "Rosewood Indian", "material_code": None,
     "material_family": "Wood", "finish": "Matte oiled", "color_name": "Indian rosewood", "color_hex": "#4A2A18",
     "texture": "Straight grain", "page_number": None, "keywords": ["rosewood", "indian", "dark"]},
    {"brand": "Anchor Wood", "catalogue": "Anchor Premium Veneers", "material_name": "Oak Cathedral Warm", "material_code": None,
     "material_family": "Wood", "finish": "Matte", "color_name": "Warm honey oak", "color_hex": "#BC8F5A",
     "texture": "Cathedral", "page_number": None, "keywords": ["oak", "cathedral", "warm honey"]},
    {"brand": "Anchor Wood", "catalogue": "Anchor Premium Veneers", "material_name": "Maple Sugar", "material_code": None,
     "material_family": "Wood", "finish": "Satin", "color_name": "Sugar maple", "color_hex": "#D8B47A",
     "texture": "Straight grain", "page_number": None, "keywords": ["maple", "sugar", "pale"]},
    {"brand": "DesignLam", "catalogue": "DesignLam Premium Woods", "material_name": "Oak Reserve Vertical", "material_code": "DL-OR-V-11",
     "material_family": "Wood", "finish": "Matte", "color_name": "Reserve oak", "color_hex": "#B18448",
     "texture": "Vertical slat-ready", "page_number": 11, "keywords": ["oak", "reserve", "vertical", "slat"]},
    {"brand": "DesignLam", "catalogue": "DesignLam Premium Woods", "material_name": "Wenge Straight", "material_code": None,
     "material_family": "Wood", "finish": "Satin", "color_name": "Deep wenge", "color_hex": "#332018",
     "texture": "Straight grain", "page_number": None, "keywords": ["wenge", "dark", "moody"]},
]

# ---------------------------------------------------------------------------
# LAMINATES / HPL — decorative wood-look and solid finishes.
# ---------------------------------------------------------------------------
LAMINATES: list[dict[str, Any]] = [
    {"brand": "Greenlam", "catalogue": "Greenlam Laminates Catalogue Vol.14", "material_name": "Warm Oak HPL", "material_code": "GL-1141",
     "material_family": "Laminate", "finish": "Matte suede", "color_name": "Warm oak", "color_hex": "#B08050",
     "texture": "Wood grain", "page_number": 74, "keywords": ["laminate", "oak", "warm", "hpl", "wood look"]},
    {"brand": "Greenlam", "catalogue": "Greenlam Laminates Catalogue Vol.14", "material_name": "Smoked Oak Laminate", "material_code": "GL-2214",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Smoked oak", "color_hex": "#7B5936",
     "texture": "Wood grain", "page_number": 76, "keywords": ["laminate", "smoked", "oak"]},
    {"brand": "Greenlam", "catalogue": "Greenlam Laminates Catalogue Vol.14", "material_name": "Warm Ivory Solid", "material_code": "GL-1101",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm ivory", "color_hex": "#EFE6D3",
     "texture": "Smooth", "page_number": 8, "keywords": ["laminate", "solid", "ivory", "warm white"]},
    {"brand": "Greenlam", "catalogue": "Fluted Décor Panels 2024", "material_name": "Fluted Oak Panel", "material_code": "GLF-OAK-16",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#B37E4D",
     "texture": "Vertical fluted", "page_number": 16, "keywords": ["fluted", "oak", "vertical", "panel", "slat"]},
    {"brand": "Merino", "catalogue": "Merino Laminates 2024", "material_name": "Natural Oak Décor HPL", "material_code": "M-1054",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Natural oak", "color_hex": "#BC8B54",
     "texture": "Wood grain", "page_number": 22, "keywords": ["laminate", "oak", "natural"]},
    {"brand": "Merino", "catalogue": "Merino Laminates 2024", "material_name": "Warm Walnut Décor HPL", "material_code": "M-2210",
     "material_family": "Laminate", "finish": "Suede", "color_name": "Warm walnut", "color_hex": "#664021",
     "texture": "Wood grain", "page_number": 41, "keywords": ["laminate", "walnut", "warm"]},
    {"brand": "Merino", "catalogue": "Merino Laminates 2024", "material_name": "Cotton White HPL", "material_code": "M-8802",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Cotton white", "color_hex": "#F5F1EA",
     "texture": "Smooth", "page_number": 3, "keywords": ["laminate", "white", "solid", "matte"]},
    {"brand": "Merino", "catalogue": "Fluted Décor Series", "material_name": "Fluted Walnut Panel", "material_code": "MF-WAL-04",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm walnut", "color_hex": "#69432A",
     "texture": "Vertical fluted", "page_number": 4, "keywords": ["fluted", "walnut", "panel", "slat", "vertical"]},
    {"brand": "Century Laminates", "catalogue": "Century Laminates 2024", "material_name": "Warm Oak Décor", "material_code": "CL-2231",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#B48753",
     "texture": "Wood grain", "page_number": 55, "keywords": ["laminate", "oak", "warm", "hpl"]},
    {"brand": "Century Laminates", "catalogue": "Century Laminates 2024", "material_name": "Ivory Solid", "material_code": "CL-1002",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Ivory", "color_hex": "#F0E9D6",
     "texture": "Smooth", "page_number": 4, "keywords": ["laminate", "ivory", "solid", "warm white"]},
    {"brand": "Sundek", "catalogue": "Sundek Décor Laminates", "material_name": "Warm Oak Straight", "material_code": None,
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#AE7F4E",
     "texture": "Straight grain", "page_number": None, "keywords": ["laminate", "oak", "warm"]},
    {"brand": "Sundek", "catalogue": "Sundek Décor Laminates", "material_name": "Cream Wave Solid", "material_code": None,
     "material_family": "Laminate", "finish": "Matte", "color_name": "Cream", "color_hex": "#EEDFC4",
     "texture": "Smooth", "page_number": None, "keywords": ["laminate", "cream", "solid"]},
    {"brand": "Formica", "catalogue": "Formica Woods & Solids", "material_name": "European Oak 8834", "material_code": "8834",
     "material_family": "Laminate", "finish": "Matte", "color_name": "European oak", "color_hex": "#B38754",
     "texture": "Wood grain", "page_number": 12, "keywords": ["formica", "oak", "european", "laminate"]},
    {"brand": "Formica", "catalogue": "Formica Woods & Solids", "material_name": "Cotton Solid 8110", "material_code": "8110",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Cotton white", "color_hex": "#F3EEE1",
     "texture": "Smooth", "page_number": 4, "keywords": ["formica", "cotton", "white", "solid"]},
    {"brand": "Wilsonart", "catalogue": "Wilsonart AEON Woods", "material_name": "Studio Oak AEON", "material_code": "8202-60",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Studio oak", "color_hex": "#AD7C4A",
     "texture": "Wood grain", "page_number": 22, "keywords": ["wilsonart", "oak", "studio"]},
    {"brand": "Advance Décor", "catalogue": "Advance HPL 2024", "material_name": "Warm Oak Advance", "material_code": None,
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#B78450",
     "texture": "Wood grain", "page_number": None, "keywords": ["laminate", "oak", "advance"]},
    {"brand": "Royale Touche", "catalogue": "Royale Décor Series", "material_name": "Warm Walnut Décor", "material_code": None,
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm walnut", "color_hex": "#6A4128",
     "texture": "Wood grain", "page_number": None, "keywords": ["laminate", "walnut", "royale"]},
    {"brand": "Duroply", "catalogue": "Duro Fluted MDF 2024", "material_name": "Fluted MDF Oak Skin", "material_code": None,
     "material_family": "Laminate", "finish": "Matte", "color_name": "Oak veneered", "color_hex": "#B78554",
     "texture": "Vertical fluted", "page_number": None, "keywords": ["fluted", "mdf", "oak", "slat", "panel"]},
    {"brand": "Action Tesa", "catalogue": "Action Décor Panels", "material_name": "Fluted Décor Panel — Oak", "material_code": "ATD-FL-01",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#B58453",
     "texture": "Vertical fluted", "page_number": 4, "keywords": ["fluted", "oak", "panel", "action tesa"]},
    {"brand": "Action Tesa", "catalogue": "Action Décor Panels", "material_name": "Fluted Décor Panel — Walnut", "material_code": "ATD-FL-02",
     "material_family": "Laminate", "finish": "Matte", "color_name": "Warm walnut", "color_hex": "#6C4128",
     "texture": "Vertical fluted", "page_number": 5, "keywords": ["fluted", "walnut", "panel"]},
]

# ---------------------------------------------------------------------------
# STONE — marble, quartzite, engineered quartz, granite.
# ---------------------------------------------------------------------------
STONE: list[dict[str, Any]] = [
    {"brand": "RK Marble", "catalogue": "Indian Marble Portfolio", "material_name": "Katni Beige Marble", "material_code": None,
     "material_family": "Stone", "finish": "Honed", "color_name": "Warm beige with fine veining", "color_hex": "#D6C4A6",
     "texture": "Fine veining", "page_number": None, "keywords": ["marble", "katni", "beige", "veined", "honed"]},
    {"brand": "RK Marble", "catalogue": "Indian Marble Portfolio", "material_name": "Makrana Cream", "material_code": None,
     "material_family": "Stone", "finish": "Polished", "color_name": "Cream white", "color_hex": "#ECE2CD",
     "texture": "Fine cloudy veins", "page_number": None, "keywords": ["marble", "makrana", "cream", "white"]},
    {"brand": "RK Marble", "catalogue": "Italian Imports 2024", "material_name": "Statuario Classic", "material_code": None,
     "material_family": "Stone", "finish": "Polished", "color_name": "White with grey veining", "color_hex": "#E9E7DE",
     "texture": "Bold veining", "page_number": None, "keywords": ["marble", "statuario", "italian", "grey vein"]},
    {"brand": "Bhandari Marble", "catalogue": "Bhandari Premium Marble", "material_name": "Botticino Classico", "material_code": None,
     "material_family": "Stone", "finish": "Polished", "color_name": "Warm beige", "color_hex": "#D9C39F",
     "texture": "Subtle veining", "page_number": None, "keywords": ["marble", "botticino", "beige", "italian"]},
    {"brand": "Bhandari Marble", "catalogue": "Bhandari Premium Marble", "material_name": "Kota Beige Limestone", "material_code": None,
     "material_family": "Stone", "finish": "Honed", "color_name": "Sand beige", "color_hex": "#C9B48C",
     "texture": "Fine grain", "page_number": None, "keywords": ["limestone", "kota", "beige", "honed"]},
    {"brand": "Kalinga Stone", "catalogue": "Kalinga Engineered Quartz", "material_name": "Cream Delight Quartz", "material_code": "KS-CR-101",
     "material_family": "Stone", "finish": "Polished", "color_name": "Cream", "color_hex": "#EBE0CA",
     "texture": "Uniform speckle", "page_number": 8, "keywords": ["quartz", "engineered", "cream", "kalinga"]},
    {"brand": "Kalinga Stone", "catalogue": "Kalinga Engineered Quartz", "material_name": "Statuario White Quartz", "material_code": "KS-SW-201",
     "material_family": "Stone", "finish": "Polished", "color_name": "White with grey vein", "color_hex": "#EEEDE6",
     "texture": "Bold vein", "page_number": 15, "keywords": ["quartz", "statuario", "veined", "white"]},
    {"brand": "Caesarstone", "catalogue": "Caesarstone Classico", "material_name": "Frosty Carrina", "material_code": "6141",
     "material_family": "Stone", "finish": "Polished", "color_name": "White with soft grey vein", "color_hex": "#EFEBE3",
     "texture": "Cloudy vein", "page_number": 22, "keywords": ["quartz", "carrina", "caesarstone", "grey vein"]},
    {"brand": "Levantina", "catalogue": "Levantina Natural Stone", "material_name": "Crema Marfil", "material_code": None,
     "material_family": "Stone", "finish": "Polished", "color_name": "Crema", "color_hex": "#DAC7A5",
     "texture": "Fine banded", "page_number": None, "keywords": ["marble", "crema marfil", "beige", "polished"]},
    {"brand": "Levantina", "catalogue": "Levantina Natural Stone", "material_name": "Beige Quartzite", "material_code": None,
     "material_family": "Stone", "finish": "Honed", "color_name": "Warm beige", "color_hex": "#CDB58F",
     "texture": "Layered", "page_number": None, "keywords": ["quartzite", "beige", "honed"]},
    {"brand": "Kajaria", "catalogue": "Kajaria Marble Look Slabs", "material_name": "Statuario 800x1600", "material_code": "KJ-ST-800",
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "White with grey vein", "color_hex": "#EEEDE7",
     "texture": "Bold vein", "page_number": 11, "keywords": ["slab", "statuario", "kajaria", "porcelain"]},
    {"brand": "Somany", "catalogue": "Somany Slab Series", "material_name": "Botticino Slab 1200x2400", "material_code": None,
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "Warm beige", "color_hex": "#DBC4A2",
     "texture": "Fine vein", "page_number": None, "keywords": ["slab", "botticino", "somany", "porcelain"]},
    {"brand": "Nitco", "catalogue": "Nitco Marble Series", "material_name": "Onyx Amber", "material_code": None,
     "material_family": "Stone", "finish": "Polished", "color_name": "Amber gold", "color_hex": "#C99B60",
     "texture": "Translucent bands", "page_number": None, "keywords": ["onyx", "amber", "gold", "translucent"]},
    {"brand": "Rex Granite", "catalogue": "Indian Granite Slabs", "material_name": "Absolute Black Granite", "material_code": None,
     "material_family": "Stone", "finish": "Polished", "color_name": "Deep black", "color_hex": "#101010",
     "texture": "Uniform", "page_number": None, "keywords": ["granite", "black", "absolute"]},
    {"brand": "Rex Granite", "catalogue": "Indian Granite Slabs", "material_name": "Kashmir White Granite", "material_code": None,
     "material_family": "Stone", "finish": "Polished", "color_name": "White with garnet flecks", "color_hex": "#E5DAD1",
     "texture": "Speckled", "page_number": None, "keywords": ["granite", "kashmir", "white", "speckled"]},
]

# ---------------------------------------------------------------------------
# TILES — porcelain, ceramic, vitrified, wood-look.
# ---------------------------------------------------------------------------
TILES: list[dict[str, Any]] = [
    {"brand": "Kajaria", "catalogue": "Kajaria Vitrified 2024", "material_name": "Wood Oak Warm 200x1200", "material_code": "KJ-W-8801",
     "material_family": "Tile", "finish": "Matte", "color_name": "Warm oak plank", "color_hex": "#B58455",
     "texture": "Wood plank", "page_number": 21, "keywords": ["tile", "wood look", "oak", "plank", "vitrified"]},
    {"brand": "Kajaria", "catalogue": "Kajaria Vitrified 2024", "material_name": "Sand Beige Cement 600x1200", "material_code": "KJ-CE-6600",
     "material_family": "Tile", "finish": "Matte", "color_name": "Warm sand", "color_hex": "#C9B08A",
     "texture": "Cement", "page_number": 8, "keywords": ["tile", "cement look", "sand", "matte"]},
    {"brand": "Kajaria", "catalogue": "Kajaria Marble Look", "material_name": "Statuario Nano 800x1600", "material_code": None,
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "White grey vein", "color_hex": "#ECECE4",
     "texture": "Bold vein", "page_number": None, "keywords": ["tile", "marble look", "statuario"]},
    {"brand": "Somany", "catalogue": "Somany Vitrified 2024", "material_name": "Oak Plank 200x1200", "material_code": "SM-W-2245",
     "material_family": "Tile", "finish": "Matte", "color_name": "Oak", "color_hex": "#B58453",
     "texture": "Wood plank", "page_number": 14, "keywords": ["tile", "wood look", "oak", "plank"]},
    {"brand": "Somany", "catalogue": "Somany Slab Series", "material_name": "Botticino 800x1600", "material_code": None,
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "Warm beige", "color_hex": "#DBC4A2",
     "texture": "Fine vein", "page_number": None, "keywords": ["tile", "marble look", "botticino"]},
    {"brand": "Nitco", "catalogue": "Nitco Timeless Tiles", "material_name": "Concrete Warm Grey 600x1200", "material_code": None,
     "material_family": "Tile", "finish": "Matte", "color_name": "Warm grey", "color_hex": "#A99C8A",
     "texture": "Cement", "page_number": None, "keywords": ["tile", "concrete", "cement look", "warm grey"]},
    {"brand": "Orient Bell", "catalogue": "Orient Bell Décor Tiles", "material_name": "Terracotta Warm 300x300", "material_code": None,
     "material_family": "Tile", "finish": "Matte", "color_name": "Terracotta", "color_hex": "#B57550",
     "texture": "Matte earth", "page_number": None, "keywords": ["tile", "terracotta", "warm", "orient bell"]},
    {"brand": "Orient Bell", "catalogue": "Orient Bell Décor Tiles", "material_name": "Ivory Marble 600x600", "material_code": None,
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "Ivory", "color_hex": "#EDE4CE",
     "texture": "Subtle vein", "page_number": None, "keywords": ["tile", "ivory", "marble look"]},
    {"brand": "RAK Ceramics", "catalogue": "RAK Maximus 2024", "material_name": "Calacatta Gold Slab", "material_code": "RAK-CG-1622",
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "White with gold vein", "color_hex": "#EFE9DB",
     "texture": "Bold gold vein", "page_number": 12, "keywords": ["tile", "calacatta", "gold", "large slab"]},
    {"brand": "RAK Ceramics", "catalogue": "RAK Wood Look Series", "material_name": "Rovere Warm Oak 200x1200", "material_code": "RAK-W-208",
     "material_family": "Tile", "finish": "Matte", "color_name": "Warm oak", "color_hex": "#B58453",
     "texture": "Wood plank", "page_number": 8, "keywords": ["tile", "wood look", "oak", "warm"]},
    {"brand": "Simpolo", "catalogue": "Simpolo Décor Series", "material_name": "Warm Beige Cement 600x600", "material_code": None,
     "material_family": "Tile", "finish": "Matte", "color_name": "Warm beige", "color_hex": "#C7B08D",
     "texture": "Cement", "page_number": None, "keywords": ["tile", "cement", "warm beige"]},
    {"brand": "AGL Tiles", "catalogue": "AGL Wonder Slabs", "material_name": "Onyx Amber Slab", "material_code": None,
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "Amber gold onyx", "color_hex": "#C89963",
     "texture": "Onyx bands", "page_number": None, "keywords": ["tile", "onyx", "amber", "translucent"]},
    {"brand": "Kajaria", "catalogue": "Kajaria Décor Highlighter", "material_name": "Terrazzo Warm 600x600", "material_code": None,
     "material_family": "Tile", "finish": "Matte", "color_name": "Warm terrazzo", "color_hex": "#CBB799",
     "texture": "Terrazzo chips", "page_number": None, "keywords": ["tile", "terrazzo", "warm"]},
    {"brand": "Kajaria", "catalogue": "Kajaria Wall Tiles", "material_name": "Ivory Matte 300x600", "material_code": None,
     "material_family": "Tile", "finish": "Matte", "color_name": "Warm ivory", "color_hex": "#EEE4CE",
     "texture": "Smooth", "page_number": None, "keywords": ["tile", "wall", "ivory", "matte"]},
    {"brand": "Nexion (Simpolo)", "catalogue": "Nexion Book-Match Series", "material_name": "Statuario Book-Match 1600x3200", "material_code": None,
     "material_family": "Tile", "finish": "Polished glazed", "color_name": "White with grey vein", "color_hex": "#EEEDE5",
     "texture": "Book-match vein", "page_number": None, "keywords": ["tile", "book match", "statuario", "large slab"]},
]

# ---------------------------------------------------------------------------
# FABRIC / TEXTILE — upholstery, drapery, bedding.
# ---------------------------------------------------------------------------
FABRIC: list[dict[str, Any]] = [
    {"brand": "Fabindia", "catalogue": "Fabindia Home 2024", "material_name": "Ivory Linen Bedding", "material_code": None,
     "material_family": "Fabric", "finish": "Soft matte", "color_name": "Warm ivory", "color_hex": "#ECE1CA",
     "texture": "Woven linen", "page_number": None, "keywords": ["linen", "ivory", "bedding", "warm"]},
    {"brand": "Fabindia", "catalogue": "Fabindia Home 2024", "material_name": "Natural Cotton Slub", "material_code": None,
     "material_family": "Fabric", "finish": "Matte", "color_name": "Natural ecru", "color_hex": "#E8DDC5",
     "texture": "Slub weave", "page_number": None, "keywords": ["cotton", "slub", "ecru", "natural"]},
    {"brand": "Fabindia", "catalogue": "Fabindia Home 2024", "material_name": "Handloom Beige Throw", "material_code": None,
     "material_family": "Fabric", "finish": "Matte", "color_name": "Warm beige", "color_hex": "#D9C6A2",
     "texture": "Handloom weave", "page_number": None, "keywords": ["handloom", "beige", "throw"]},
    {"brand": "Sarita Handa", "catalogue": "Sarita Handa Bed & Bath", "material_name": "Organic Cotton Sateen Set", "material_code": None,
     "material_family": "Fabric", "finish": "Soft sheen", "color_name": "Ivory", "color_hex": "#EEE1CB",
     "texture": "Sateen", "page_number": None, "keywords": ["cotton", "sateen", "organic", "ivory"]},
    {"brand": "Sarita Handa", "catalogue": "Sarita Handa Bed & Bath", "material_name": "Linen Slub Bedcover", "material_code": None,
     "material_family": "Fabric", "finish": "Matte", "color_name": "Sand", "color_hex": "#D5C29C",
     "texture": "Slub linen", "page_number": None, "keywords": ["linen", "slub", "sand", "bedcover"]},
    {"brand": "D'Decor", "catalogue": "D'Decor Upholstery Vol.9", "material_name": "Boucle Cream Upholstery", "material_code": None,
     "material_family": "Fabric", "finish": "Textured", "color_name": "Cream boucle", "color_hex": "#E9DDC3",
     "texture": "Loop pile bouclé", "page_number": None, "keywords": ["boucle", "cream", "upholstery"]},
    {"brand": "D'Decor", "catalogue": "D'Decor Upholstery Vol.9", "material_name": "Warm Sand Boucle", "material_code": None,
     "material_family": "Fabric", "finish": "Textured", "color_name": "Sand", "color_hex": "#D6BF98",
     "texture": "Loop pile bouclé", "page_number": None, "keywords": ["boucle", "sand", "upholstery"]},
    {"brand": "D'Decor", "catalogue": "D'Decor Sheer Series", "material_name": "Sheer Ivory Linen Panel", "material_code": None,
     "material_family": "Fabric", "finish": "Soft drape", "color_name": "Ivory", "color_hex": "#F0E7D0",
     "texture": "Loose weave", "page_number": None, "keywords": ["sheer", "linen", "ivory", "curtain"]},
    {"brand": "Deco Window", "catalogue": "Deco Window 2024", "material_name": "Sheer Warm White Panel", "material_code": None,
     "material_family": "Fabric", "finish": "Soft drape", "color_name": "Warm white", "color_hex": "#F2ECD8",
     "texture": "Loose weave", "page_number": None, "keywords": ["sheer", "white", "curtain"]},
    {"brand": "Deco Window", "catalogue": "Deco Window 2024", "material_name": "Poly-Linen Blend Panel", "material_code": None,
     "material_family": "Fabric", "finish": "Matte drape", "color_name": "Warm ivory", "color_hex": "#EEE3CD",
     "texture": "Blend weave", "page_number": None, "keywords": ["poly linen", "blend", "curtain"]},
    {"brand": "The White Window", "catalogue": "TWW Curated Curtains", "material_name": "Handloom Linen Curtain", "material_code": None,
     "material_family": "Fabric", "finish": "Soft drape", "color_name": "Ivory", "color_hex": "#EEE1CA",
     "texture": "Handloom", "page_number": None, "keywords": ["handloom", "linen", "curtain", "ivory"]},
    {"brand": "Jaipur Rugs", "catalogue": "Manchaha Collection", "material_name": "Hand-Knotted Wool — Sand", "material_code": None,
     "material_family": "Fabric", "finish": "Hand-knotted matte", "color_name": "Sand beige", "color_hex": "#D3BE96",
     "texture": "Low-loop wool", "page_number": None, "keywords": ["rug", "wool", "hand knotted", "sand"]},
    {"brand": "Obeetee", "catalogue": "Obeetee Studio Rugs", "material_name": "Hand-Tufted Wool Cream", "material_code": None,
     "material_family": "Fabric", "finish": "Hand-tufted", "color_name": "Cream", "color_hex": "#E5D6B9",
     "texture": "Loop pile", "page_number": None, "keywords": ["rug", "wool", "hand tufted", "cream"]},
    {"brand": "Cocoon", "catalogue": "Cocoon Textured Rugs", "material_name": "Jute Warm Sand", "material_code": None,
     "material_family": "Fabric", "finish": "Textured", "color_name": "Warm sand", "color_hex": "#CDB48C",
     "texture": "Jute weave", "page_number": None, "keywords": ["rug", "jute", "warm sand", "natural"]},
    {"brand": "House of MG", "catalogue": "HoMG Textiles 2024", "material_name": "Linen-Cotton Blend Bedding", "material_code": None,
     "material_family": "Fabric", "finish": "Soft matte", "color_name": "Warm ivory", "color_hex": "#EDDFC5",
     "texture": "Blend weave", "page_number": None, "keywords": ["linen cotton", "blend", "bedding"]},
]

# ---------------------------------------------------------------------------
# LIGHTING — pendants, wall sconces, floor lamps.
# ---------------------------------------------------------------------------
LIGHTING: list[dict[str, Any]] = [
    {"brand": "Havells", "catalogue": "Havells Décor 2024", "material_name": "Brushed Brass Pendant Cone", "material_code": None,
     "material_family": "Lighting", "finish": "Brushed brass", "color_name": "Warm brass", "color_hex": "#B18C4D",
     "texture": "Brushed metal", "page_number": None, "keywords": ["pendant", "brass", "warm", "cone"]},
    {"brand": "Philips", "catalogue": "Philips Décor Lighting", "material_name": "Warm White LED Pendant", "material_code": "PHL-DP-102",
     "material_family": "Lighting", "finish": "Satin white", "color_name": "Warm white", "color_hex": "#F3E7C7",
     "texture": "Smooth", "page_number": 8, "keywords": ["pendant", "led", "warm white"]},
    {"brand": "Fabuliv", "catalogue": "Fabuliv Ambient Lights", "material_name": "Rattan Dome Pendant", "material_code": None,
     "material_family": "Lighting", "finish": "Natural rattan", "color_name": "Warm natural", "color_hex": "#C7A26F",
     "texture": "Woven rattan", "page_number": None, "keywords": ["pendant", "rattan", "natural", "warm"]},
    {"brand": "Whispering Homes", "catalogue": "WH Décor Lighting", "material_name": "Fluted Glass Wall Sconce", "material_code": None,
     "material_family": "Lighting", "finish": "Brass + glass", "color_name": "Warm brass", "color_hex": "#B58C4D",
     "texture": "Fluted glass", "page_number": None, "keywords": ["sconce", "fluted glass", "brass"]},
    {"brand": "Jainsons Emporio", "catalogue": "Jainsons Décor 2024", "material_name": "Marble Base Table Lamp", "material_code": None,
     "material_family": "Lighting", "finish": "Marble + brass", "color_name": "Cream marble", "color_hex": "#E5D8BD",
     "texture": "Marble", "page_number": None, "keywords": ["table lamp", "marble", "brass"]},
    {"brand": "Whitteny", "catalogue": "Whitteny Lighting", "material_name": "Warm Metal Reading Sconce", "material_code": None,
     "material_family": "Lighting", "finish": "Antique brass", "color_name": "Antique brass", "color_hex": "#9A7A4A",
     "texture": "Brushed", "page_number": None, "keywords": ["reading sconce", "brass", "bedside"]},
    {"brand": "The White Teak Co.", "catalogue": "WTC Modern Lighting", "material_name": "Slim Brass Floor Lamp", "material_code": None,
     "material_family": "Lighting", "finish": "Satin brass", "color_name": "Warm brass", "color_hex": "#B78D53",
     "texture": "Slim tube", "page_number": None, "keywords": ["floor lamp", "brass", "slim", "modern"]},
    {"brand": "Wipro Lighting", "catalogue": "Wipro Décor 2024", "material_name": "Cove LED Warm White 3000K", "material_code": "WP-CV-3000",
     "material_family": "Lighting", "finish": "Aluminium extrusion", "color_name": "Warm white LED", "color_hex": "#F5E7BE",
     "texture": "Linear", "page_number": 4, "keywords": ["cove", "led", "warm white", "linear"]},
    {"brand": "Panasonic", "catalogue": "Panasonic Anchor Décor Lighting", "material_name": "Recessed Warm White Downlight 9W", "material_code": "PN-DL-9W",
     "material_family": "Lighting", "finish": "White powder coat", "color_name": "Warm white", "color_hex": "#F4E9C4",
     "texture": "Recessed", "page_number": None, "keywords": ["downlight", "recessed", "warm white"]},
    {"brand": "Beem Décor", "catalogue": "Beem Décor Pendants", "material_name": "Fluted Glass Pendant Warm", "material_code": None,
     "material_family": "Lighting", "finish": "Fluted glass + brass", "color_name": "Amber glass", "color_hex": "#C79C5F",
     "texture": "Fluted amber", "page_number": None, "keywords": ["pendant", "fluted", "amber", "warm"]},
]

# ---------------------------------------------------------------------------
# HARDWARE — handles, profiles, mouldings.
# ---------------------------------------------------------------------------
HARDWARE: list[dict[str, Any]] = [
    {"brand": "Häfele India", "catalogue": "Häfele Hardware Collection", "material_name": "Brass Cove Profile 12mm", "material_code": "HF-BR-12",
     "material_family": "Metal", "finish": "Brushed brass", "color_name": "Antique brass", "color_hex": "#B18C4D",
     "texture": "Brushed", "page_number": 22, "keywords": ["profile", "cove", "brass", "trim"]},
    {"brand": "Häfele India", "catalogue": "Häfele Hardware Collection", "material_name": "Rose Gold Steel Trim", "material_code": "HF-RG-08",
     "material_family": "Metal", "finish": "Satin", "color_name": "Rose gold", "color_hex": "#C68B6F",
     "texture": "Satin", "page_number": 24, "keywords": ["trim", "rose gold", "steel"]},
    {"brand": "Häfele India", "catalogue": "Häfele Handles 2024", "material_name": "Slim Brass Pull Handle 320mm", "material_code": None,
     "material_family": "Metal", "finish": "Brushed brass", "color_name": "Warm brass", "color_hex": "#B58C4D",
     "texture": "Slim tube", "page_number": None, "keywords": ["handle", "brass", "slim", "pull"]},
    {"brand": "Hettich", "catalogue": "Hettich India Hardware", "material_name": "Concealed Hinge — Soft Close", "material_code": "HET-CH-SC",
     "material_family": "Metal", "finish": "Nickel plated", "color_name": "Nickel", "color_hex": "#B5B5B5",
     "texture": "Machined", "page_number": None, "keywords": ["hinge", "soft close", "concealed"]},
    {"brand": "Blum", "catalogue": "Blum Movement Systems", "material_name": "Tandembox Antaro", "material_code": None,
     "material_family": "Metal", "finish": "Silver", "color_name": "Silk white", "color_hex": "#E9E4DA",
     "texture": "Smooth", "page_number": None, "keywords": ["drawer", "antaro", "tandembox"]},
    {"brand": "Ebco", "catalogue": "Ebco India Hardware 2024", "material_name": "Fluted Brass Wall Cladding Strip", "material_code": None,
     "material_family": "Metal", "finish": "Brushed brass", "color_name": "Warm brass", "color_hex": "#B78D53",
     "texture": "Fluted", "page_number": None, "keywords": ["fluted", "brass", "cladding", "wall"]},
    {"brand": "Godrej Locks", "catalogue": "Godrej Handles 2024", "material_name": "Modern Rose Gold Handle 200mm", "material_code": None,
     "material_family": "Metal", "finish": "Rose gold satin", "color_name": "Rose gold", "color_hex": "#C58E70",
     "texture": "Satin", "page_number": None, "keywords": ["handle", "rose gold", "modern"]},
    {"brand": "Jaquar Artize", "catalogue": "Artize Basin Fittings", "material_name": "Brushed Brass Basin Faucet", "material_code": "AZ-BB-101",
     "material_family": "Metal", "finish": "Brushed brass", "color_name": "Warm brass", "color_hex": "#B58C4D",
     "texture": "Brushed", "page_number": None, "keywords": ["faucet", "brass", "brushed", "artize"]},
    {"brand": "Jindal Stainless", "catalogue": "Jindal PVD Coloured Steel", "material_name": "Rose Gold PVD Sheet", "material_code": None,
     "material_family": "Metal", "finish": "PVD satin", "color_name": "Rose gold", "color_hex": "#C6896D",
     "texture": "Sheet", "page_number": None, "keywords": ["pvd", "rose gold", "steel", "sheet"]},
    {"brand": "Jindal Stainless", "catalogue": "Jindal PVD Coloured Steel", "material_name": "Antique Brass PVD Sheet", "material_code": None,
     "material_family": "Metal", "finish": "PVD satin", "color_name": "Antique brass", "color_hex": "#A98547",
     "texture": "Sheet", "page_number": None, "keywords": ["pvd", "antique brass", "steel"]},
]

# ---------------------------------------------------------------------------
# FURNITURE — hero pieces stocked by Indian design studios.
# ---------------------------------------------------------------------------
FURNITURE: list[dict[str, Any]] = [
    {"brand": "Godrej Interio", "catalogue": "Godrej Interio Home 2024", "material_name": "Warm Oak Platform Bed King", "material_code": None,
     "material_family": "Furniture", "finish": "Oak veneer + matte", "color_name": "Warm oak", "color_hex": "#B0824F",
     "texture": "Wood grain", "page_number": None, "keywords": ["bed", "platform", "oak", "king"]},
    {"brand": "Urban Ladder", "catalogue": "Urban Ladder Bedroom", "material_name": "Bouclé Upholstered Headboard", "material_code": None,
     "material_family": "Furniture", "finish": "Bouclé fabric", "color_name": "Cream boucle", "color_hex": "#E5D7BB",
     "texture": "Bouclé loop", "page_number": None, "keywords": ["headboard", "boucle", "upholstered"]},
    {"brand": "Pepperfry", "catalogue": "Studio Pepperfry", "material_name": "Warm Walnut Nightstand", "material_code": None,
     "material_family": "Furniture", "finish": "Walnut veneer", "color_name": "Warm walnut", "color_hex": "#6E4A2E",
     "texture": "Wood grain", "page_number": None, "keywords": ["nightstand", "walnut", "warm"]},
    {"brand": "Pepperfry", "catalogue": "Studio Pepperfry", "material_name": "Bouclé Reading Chair", "material_code": None,
     "material_family": "Furniture", "finish": "Bouclé fabric", "color_name": "Cream", "color_hex": "#E5D6B9",
     "texture": "Bouclé loop", "page_number": None, "keywords": ["chair", "boucle", "reading"]},
    {"brand": "IKEA India", "catalogue": "IKEA Bedroom 2024", "material_name": "Malm Oak Effect Dresser", "material_code": None,
     "material_family": "Furniture", "finish": "Oak veneer", "color_name": "Warm oak", "color_hex": "#B1834F",
     "texture": "Wood grain", "page_number": None, "keywords": ["dresser", "malm", "oak", "storage"]},
    {"brand": "Gulmohar Lane", "catalogue": "Gulmohar Bedroom", "material_name": "Slim Brass Nightstand", "material_code": None,
     "material_family": "Furniture", "finish": "Wood + brass", "color_name": "Walnut + brass", "color_hex": "#6E4A2E",
     "texture": "Wood + metal", "page_number": None, "keywords": ["nightstand", "brass", "slim", "walnut"]},
    {"brand": "The Wishing Chair", "catalogue": "TWC Studio Collection", "material_name": "Cane Backrest Accent Chair", "material_code": None,
     "material_family": "Furniture", "finish": "Cane + wood", "color_name": "Natural cane", "color_hex": "#C7A26F",
     "texture": "Woven cane", "page_number": None, "keywords": ["accent chair", "cane", "natural"]},
    {"brand": "West Elm India", "catalogue": "West Elm Bedroom", "material_name": "Mid-Century Oak Bench", "material_code": None,
     "material_family": "Furniture", "finish": "Oak + upholstery", "color_name": "Warm oak", "color_hex": "#B0834F",
     "texture": "Wood grain", "page_number": None, "keywords": ["bench", "mid century", "oak"]},
    {"brand": "Home Centre", "catalogue": "Home Centre Décor", "material_name": "Ivory Bouclé Ottoman", "material_code": None,
     "material_family": "Furniture", "finish": "Bouclé", "color_name": "Ivory", "color_hex": "#E9DEC4",
     "texture": "Bouclé", "page_number": None, "keywords": ["ottoman", "boucle", "ivory"]},
    {"brand": "Chumbak", "catalogue": "Chumbak Home 2024", "material_name": "Warm Wood Console", "material_code": None,
     "material_family": "Furniture", "finish": "Wood + matte", "color_name": "Warm oak", "color_hex": "#B48354",
     "texture": "Wood grain", "page_number": None, "keywords": ["console", "wood", "warm oak"]},
]

# ---------------------------------------------------------------------------
# PAINTS — Asian Paints, Berger, Nerolac, Dulux.  We NEVER fabricate official
# shade codes.  Codes below are only those we're confident about; else `None`
# and the API renders "Code unavailable in current database".
# ---------------------------------------------------------------------------
PAINTS: list[dict[str, Any]] = [
    # -------- Asian Paints -------- (~18)
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Cotton White", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Cotton white", "color_hex": "#F3EEE0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "warm white", "cotton", "royale", "asian paints"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Warm Ivory", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm ivory", "color_hex": "#EFE4CB",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "warm", "ivory", "royale"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Almond Whisper", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm almond", "color_hex": "#EBDCC0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "almond", "warm cream"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Peach Cream", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Soft peach", "color_hex": "#F2D9BE",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "peach", "warm cream"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Pearl Blossom", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Pearl blossom", "color_hex": "#F1E5D0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "pearl", "off white"]},
    {"brand": "Asian Paints", "catalogue": "Royale Play Textures", "material_name": "Sandstone Warm Texture", "material_code": None,
     "material_family": "Paint", "finish": "Textured", "color_name": "Warm sand", "color_hex": "#D9C29B",
     "texture": "Sandstone", "page_number": None, "keywords": ["paint", "texture", "sandstone", "warm"]},
    {"brand": "Asian Paints", "catalogue": "Royale Play Textures", "material_name": "Travertine Cream Texture", "material_code": None,
     "material_family": "Paint", "finish": "Textured", "color_name": "Cream travertine", "color_hex": "#E1D2AC",
     "texture": "Travertine", "page_number": None, "keywords": ["paint", "texture", "travertine", "cream"]},
    {"brand": "Asian Paints", "catalogue": "Ultima Weather Pro", "material_name": "Weather White", "material_code": None,
     "material_family": "Paint", "finish": "Semi-matte", "color_name": "Cool white", "color_hex": "#F5F3EE",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "weather", "white"]},
    {"brand": "Asian Paints", "catalogue": "Ultima Weather Pro", "material_name": "Weather Beige", "material_code": None,
     "material_family": "Paint", "finish": "Semi-matte", "color_name": "Warm beige", "color_hex": "#D6C4A2",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "weather", "beige"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Ivory Sand", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Ivory sand", "color_hex": "#ECDDBF",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "ivory", "sand", "warm neutral"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Old Ivory", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Old ivory", "color_hex": "#E9DDBE",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "old ivory", "classic"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Wheat Cream", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Wheat", "color_hex": "#E4D0A1",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "wheat", "cream", "warm"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Deep Charcoal", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Deep charcoal", "color_hex": "#3A3A3A",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "charcoal", "dark", "moody"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Terracotta Warm", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm terracotta", "color_hex": "#B37050",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "terracotta", "warm accent"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Warm Grey Mist", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm grey", "color_hex": "#B7ADA0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "warm grey", "neutral"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Sage Whisper", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Soft sage", "color_hex": "#C1CBB5",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "sage", "soft green"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Muted Olive", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Muted olive", "color_hex": "#8F8B65",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "olive", "muted", "green"]},
    {"brand": "Asian Paints", "catalogue": "Colour Spectra — Royale", "material_name": "Dusty Rose", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Dusty rose", "color_hex": "#D4A99B",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "rose", "dusty pink"]},

    # -------- Berger -------- (~16)
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Ivory", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Warm ivory", "color_hex": "#EEE2C8",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "silk", "ivory", "berger"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Warm White", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Warm white", "color_hex": "#F2ECD8",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "silk", "warm white"]},
    {"brand": "Berger", "catalogue": "Silk Glamour Emulsion", "material_name": "Silk Glamour Cream", "material_code": None,
     "material_family": "Paint", "finish": "Silk sheen", "color_name": "Cream", "color_hex": "#F1E4C6",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "silk glamour", "cream"]},
    {"brand": "Berger", "catalogue": "Silk Glamour Emulsion", "material_name": "Silk Glamour Peach", "material_code": None,
     "material_family": "Paint", "finish": "Silk sheen", "color_name": "Peach", "color_hex": "#F3D6B6",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "peach", "silk"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Almond", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Warm almond", "color_hex": "#EFE0C0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "almond", "warm"]},
    {"brand": "Berger", "catalogue": "Weathercoat Long Life", "material_name": "Weathercoat Warm White", "material_code": None,
     "material_family": "Paint", "finish": "Semi-matte", "color_name": "Warm white", "color_hex": "#F4EDD9",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "weathercoat", "white"]},
    {"brand": "Berger", "catalogue": "Weathercoat Long Life", "material_name": "Weathercoat Cream", "material_code": None,
     "material_family": "Paint", "finish": "Semi-matte", "color_name": "Warm cream", "color_hex": "#EDE0BF",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "cream"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Sand", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Warm sand", "color_hex": "#D9C29C",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "sand", "warm neutral"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Charcoal", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Deep charcoal", "color_hex": "#3B3B3B",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "charcoal", "dark"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Warm Grey", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Warm grey", "color_hex": "#B7ADA0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "warm grey"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Sage", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Soft sage", "color_hex": "#BFC9B3",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "sage", "soft"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Dusty Rose", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Dusty rose", "color_hex": "#D4A99B",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "rose", "dusty"]},
    {"brand": "Berger", "catalogue": "Weathercoat Anti-Dust", "material_name": "Weathercoat Beige", "material_code": None,
     "material_family": "Paint", "finish": "Semi-matte", "color_name": "Warm beige", "color_hex": "#D6C4A2",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "beige"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Wheat", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Wheat", "color_hex": "#E4D0A1",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "wheat", "warm cream"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Terracotta", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Warm terracotta", "color_hex": "#B37050",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "terracotta"]},
    {"brand": "Berger", "catalogue": "Silk Breathe Easy", "material_name": "Silk Breathe Olive", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Muted olive", "color_hex": "#8F8B65",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "olive", "muted green"]},

    # -------- Nerolac -------- (~14)
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Warm White", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm white", "color_hex": "#F3ECD8",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "impressions", "warm white", "nerolac"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Ivory Peach", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Ivory peach", "color_hex": "#F2DFC4",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "ivory", "peach"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Cream Silk", "material_code": None,
     "material_family": "Paint", "finish": "Silk", "color_name": "Cream", "color_hex": "#F0E2C4",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "cream", "silk"]},
    {"brand": "Nerolac", "catalogue": "Excel Total", "material_name": "Excel Off White", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Off white", "color_hex": "#F1EDDF",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "excel", "off white"]},
    {"brand": "Nerolac", "catalogue": "Excel Total", "material_name": "Excel Warm Beige", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm beige", "color_hex": "#D6C4A2",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "beige"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Sand", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm sand", "color_hex": "#D9C29C",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "sand", "warm"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Almond", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Almond", "color_hex": "#EBDCC0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "almond"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Charcoal", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Charcoal", "color_hex": "#3B3B3B",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "charcoal", "dark"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Warm Grey", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm grey", "color_hex": "#B7ADA0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "warm grey"]},
    {"brand": "Nerolac", "catalogue": "Beautiful Home Colours", "material_name": "Cotton Cream", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Cotton cream", "color_hex": "#EDDFC0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "cotton cream"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Terracotta", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Terracotta", "color_hex": "#B37050",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "terracotta"]},
    {"brand": "Nerolac", "catalogue": "Impressions HD", "material_name": "Impressions Sage", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Sage", "color_hex": "#C1CBB5",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "sage", "green"]},
    {"brand": "Nerolac", "catalogue": "Impressions Metallica", "material_name": "Metallica Warm Gold", "material_code": None,
     "material_family": "Paint", "finish": "Metallic", "color_name": "Warm gold", "color_hex": "#B78D53",
     "texture": "Metallic", "page_number": None, "keywords": ["paint", "metallica", "gold"]},
    {"brand": "Nerolac", "catalogue": "Impressions Metallica", "material_name": "Metallica Rose Gold", "material_code": None,
     "material_family": "Paint", "finish": "Metallic", "color_name": "Rose gold", "color_hex": "#C6896D",
     "texture": "Metallic", "page_number": None, "keywords": ["paint", "metallica", "rose gold"]},

    # -------- Dulux -------- (~14)
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Antique White", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Antique white", "color_hex": "#EFE5CB",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "velvet", "antique white", "dulux"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Almond White", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Almond white", "color_hex": "#EEE1C6",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "almond", "velvet"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Warm Ivory", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm ivory", "color_hex": "#EFE4CB",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "warm ivory"]},
    {"brand": "Dulux", "catalogue": "Weathershield Max", "material_name": "Weathershield Ivory", "material_code": None,
     "material_family": "Paint", "finish": "Semi-matte", "color_name": "Ivory", "color_hex": "#EFE4CB",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "weathershield"]},
    {"brand": "Dulux", "catalogue": "Weathershield Max", "material_name": "Weathershield Warm White", "material_code": None,
     "material_family": "Paint", "finish": "Semi-matte", "color_name": "Warm white", "color_hex": "#F3EED9",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "exterior", "warm white"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Sand", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm sand", "color_hex": "#D9C29C",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "sand", "warm"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Peach Cream", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Peach cream", "color_hex": "#F2D9BE",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "peach", "cream"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Charcoal Slate", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Charcoal", "color_hex": "#3B3B3B",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "charcoal"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Warm Grey", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Warm grey", "color_hex": "#B7ADA0",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "warm grey"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Sage", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Sage", "color_hex": "#BFC9B3",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "sage"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Muted Olive", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Muted olive", "color_hex": "#8F8B65",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "olive"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Dusty Rose", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Dusty rose", "color_hex": "#D4A99B",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "rose", "dusty pink"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Wheat Cream", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Wheat cream", "color_hex": "#E4D0A1",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "wheat", "cream"]},
    {"brand": "Dulux", "catalogue": "Velvet Touch Platinum Glo", "material_name": "Velvet Terracotta", "material_code": None,
     "material_family": "Paint", "finish": "Matte", "color_name": "Terracotta", "color_hex": "#B37050",
     "texture": "Smooth", "page_number": None, "keywords": ["paint", "terracotta"]},
]


# ---------------------------------------------------------------------------
# CATEGORY REGISTRY — keeps the seed grouped for the Global Library sidebar.
# ---------------------------------------------------------------------------
CATEGORY_SETS: dict[str, list[dict[str, Any]]] = {
    "Veneers": VENEERS,
    "Laminates": LAMINATES,
    "Stone": STONE,
    "Tiles": TILES,
    "Fabric": FABRIC,
    "Lighting": LIGHTING,
    "Hardware": HARDWARE,
    "Furniture": FURNITURE,
    "Paints": PAINTS,
}


def build_seeded_catalogue() -> list[dict[str, Any]]:
    """Flat list with `id`, `category` and `source` filled in.  Every item is
    marked as "Global Library" — the API tags user-uploaded PDF matches with a
    different source at query time."""
    out: list[dict[str, Any]] = []
    for cat, items in CATEGORY_SETS.items():
        for i, it in enumerate(items):
            enriched = dict(it)
            enriched["category"] = cat
            enriched["source"] = "Global Library"
            # Deterministic id derived from brand + name + index.
            enriched["id"] = f"{cat.lower()}-{i:03d}-{it['brand'].lower().replace(' ', '-')}"
            out.append(enriched)
    return out


SEEDED_CATALOGUE: list[dict[str, Any]] = build_seeded_catalogue()

# Alternative material *systems* (category-level swaps) for each family.
ALTERNATIVE_SYSTEMS: dict[str, list[dict[str, str]]] = {
    "Wood": [
        {"name": "Natural Veneer", "why": "Real wood grain, warmest look, needs periodic oiling."},
        {"name": "HPL Laminate (wood look)", "why": "Cheaper, high durability, wipe-clean."},
        {"name": "Textured Laminate", "why": "Adds tactile depth in solid or wood-look décors."},
        {"name": "PVC Decorative Panel", "why": "Water-safe budget option for humid zones."},
        {"name": "Fluted MDF Slat Panel", "why": "Same vertical slat rhythm, ready-to-fit."},
        {"name": "Wood-look Porcelain Tile", "why": "Water-resistant, near-zero maintenance."},
    ],
    "Laminate": [
        {"name": "HPL Laminate", "why": "Standard 0.8–1.2mm sheet, wide finish range."},
        {"name": "Acrylic Sheet", "why": "High-gloss modern kitchen option."},
        {"name": "Textured Laminate", "why": "Adds tactile depth in solid or wood-look décors."},
        {"name": "Fluted MDF Panel", "why": "Vertical slat aesthetic, ready to fit."},
    ],
    "Paint": [
        {"name": "Matte Emulsion", "why": "Standard interior finish across every brand."},
        {"name": "Silk / Satin Emulsion", "why": "Soft sheen, easier to clean."},
        {"name": "Limewash Finish", "why": "Chalky artisanal texture, muted patina."},
        {"name": "Textured Plaster / Micro-cement", "why": "Depth via trowelled texture."},
        {"name": "Wallpaper", "why": "Pattern option when a solid colour feels flat."},
    ],
    "Stone": [
        {"name": "Natural Marble", "why": "Classic look, needs sealing."},
        {"name": "Quartzite", "why": "Harder, less staining than marble."},
        {"name": "Engineered Quartz", "why": "Consistent pattern, non-porous, budget-friendly."},
        {"name": "Porcelain Slab (marble-look)", "why": "Ultra-durable, waterproof, big formats."},
    ],
    "Tile": [
        {"name": "Vitrified Tile", "why": "Standard workhorse for floors."},
        {"name": "Porcelain Slab (large format)", "why": "Fewer joints, monolithic look."},
        {"name": "Ceramic Tile", "why": "Budget option for walls."},
        {"name": "Stone-look Vinyl SPC", "why": "Click-lock over existing floor."},
    ],
    "Fabric": [
        {"name": "Washed Cotton", "why": "Budget alternative to linen."},
        {"name": "Linen", "why": "Warmest drape, natural."},
        {"name": "Linen-Cotton Blend", "why": "Warmer look with less wrinkling."},
        {"name": "Bouclé", "why": "Loop-pile texture for feature upholstery."},
        {"name": "Poly-Linen Blend", "why": "Wrinkle-resistant, easier care."},
    ],
    "Metal": [
        {"name": "Brushed Brass Steel", "why": "Warm accent, mid cost."},
        {"name": "Rose Gold PVD Steel", "why": "Modern warm metallic."},
        {"name": "Brushed Gold Aluminium", "why": "Same look, lighter, lower cost."},
    ],
    "Lighting": [
        {"name": "Brass Pendant", "why": "Ambient warm layered light."},
        {"name": "Rattan Dome Pendant", "why": "Softer natural texture."},
        {"name": "Fluted Glass Sconce", "why": "Directional accent light."},
        {"name": "Recessed LED Downlight", "why": "Baseline general illumination."},
    ],
    "Furniture": [
        {"name": "Upholstered Bouclé", "why": "Modern warm feature texture."},
        {"name": "Cane / Rattan", "why": "Natural airy texture."},
        {"name": "Wood + Metal Combo", "why": "Warm-industrial modern look."},
    ],
}
